force-app/main/default/objects/Inactive_Users_Setting_mm__mdt/Inactive_Users_Setting_mm__mdt.object-meta.xml
<CustomObject>
    <description>General settings for freezing and inactivation automation. Only &quot;Default&quot; record must be present. Further records will be ignored.</description>
    <label>User Inactivation Setting</label>
    <pluralLabel>User Inactivation Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inactive_Users_Setting_mm__mdt/fields/Batch_Size_mm__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size_mm__c</fullName>
    <defaultValue>200</defaultValue>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UserInactivationSchedulable_mm.cls
public class UserInactivationSchedulable_mm implements Schedulable {
    public void execute(SchedulableContext sc) {
        List<Inactive_Users_Setting_mm__mdt> ius = Inactive_Users_Setting_mm__mdt.getAll().values();
        Integer batchSize = 200;
        if (ius.size() > 0 && ius[0].Batch_Size_mm__c > 0) {
            batchSize = ius[0].Batch_Size_mm__c.intValue();
        }

        UserInactivationBatch_mm b = new UserInactivationBatch_mm();
        database.executebatch(b, batchSize);
     }
}